Development
Zloooy/todo_app pull request #1
Opened 2022-08-06 17:06 UTC by Zloooy

Полностью функционирующий экран списка заявок - работает локальное сохранение и синхронизация с сетью (для запуска в корень проекта нужно поместить файл credentials.env с содержимым TOKEN=<токен>.

2022-08-07 16:15 UTC, devasidmi commented
Не должно быть 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/20377394/183300480-225100cb-dcc6-43af-8492-15ef911674be.png">

2022-08-07 16:35 UTC, devasidmi requested changes

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/adapter/color_adapter.dart
> +class ColorAdapter extends TypeAdapter<Color> {
я правильно понял, что ты решил хранить цвета?

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/data_source/network_task_data_source.dart
> +            headers: {'Authorization': 'Bearer ${dotenv.env["TOKEN"]}'}));
лучше ключи мап выносить в константы отдельный файлик, за окружение для токена респект

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/data_source/network_task_data_source.dart
> +      final resp = await _dio.get<Map<String, dynamic>>('/list');
я бы заменил все `Map<String, dynamic>` на `Map<String, Object?>`

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/data_source/network_task_data_source.dart
> +          final respMap = resp.data as Map<String, dynamic>;
не, нужно получать модельку через `fromJson`

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/data_source/network_task_data_source.dart
> +        '/list',
вынести в константы

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/data_source/network_task_data_source.dart
> +          'status': 'ok',
вынести в константы, а лучше сделать модельку и делать toJson

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/data_source/network_task_data_source.dart
> +          final respMap = resp.data as Map<String, dynamic>;
сделать модель и через fromJson парсить

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/data_source/network_task_data_source.dart
> +      final resp = await _dio.get<Map<String, dynamic>>('/list/$id');
сделать файлик с ApiPath и брать оттуда константы

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/data_source/network_task_data_source.dart
> +class NetworkTaskDataSource {
Для всего файла:
 - Сделать модели для парсинга json
 - Заменить Map<String, dynamic> на Map<String, Object?>
 - Вынести пути в отдельный файл
 - Вынести ключи мап и тд в константы

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/dto/last_known_revision_wrapper.dart
> +      {required this.lastKnownRevision, required this.value});
вроде линтер должен тут говорить про trailing comma

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/dto/task_dto.dart
> +//extension  EntityUpdater on _$TaskDto {
зачем это тут?

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/dto/task_dto.dart
> +          required String lastUpdatedBy}) = _TaskDto;
ну глаз ведь должно резать, trailing comma

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/dto/task_dto.dart
> +  factory TaskDto.fromJson(Map<String, dynamic> json) =>
везде заменить Map<String, dynamic> на Map<String, Object?>

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/dto/task_dto.dart
> +    Color? color,
в DTO не может быть Color, только классы с примитивами или просто примитивы

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/dto/task_dto.dart
> +class TimestampConverter implements JsonConverter<DateTime, int> {
это в отдельный файл

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/repository/task_repository.dart
> +      required LocalTaskDataSource localTaskDataSource})
trailing comma

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/repository/task_repository.dart
> +  Future<List<TaskEntity>> getAllTasks() async => (_localDS.getAllTasks()
не вижу await, значит async не нужен

2022-08-07 16:35 UTC, devasidmi commented on lib/core/data/repository/task_repository.dart
> +  static const List<String> _texts = [
это должно быть в отдельном файле

2022-08-07 16:35 UTC, devasidmi commented on lib/core/dependency_injection/global_provider.dart
> +  final Widget app;
если это по линтеру, то ок, но кажется правило - делать поля класса после конструктора стоит отключить

2022-08-07 16:35 UTC, devasidmi commented on lib/core/dependency_injection/global_provider.dart
> +                networkTaskDataSource: NetworkTaskDataSource())),
trailing comma

2022-08-07 16:35 UTC, devasidmi commented on lib/core/domain/entity/task_entity.dart
> +      required bool done}) = _TaskEntity;
trailing comma :(

2022-08-07 16:35 UTC, devasidmi commented on lib/core/domain/entity/task_entity.dart
> +  static TaskEntity blank() {
отступы между методами очень просятся, оч тяжело читать такой код

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list_item.dart
> +    // return Theme(
очень много комментов в коде, все они нужны?

2022-08-07 16:35 UTC, devasidmi commented on lib/core/presentation/themes/extensions/additional_colors.dart
> +      required this.transparentRed});
trailing comma 🔪

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/data/dto/short_task.dart
> +    true,
а тут не нужны trailing comma :)

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/bloc/task_list_event.dart
> +abstract class TaskListEvent {}
<img width="737" alt="image" src="https://user-images.githubusercontent.com/20377394/183300914-6a1d84a4-8d81-40c3-8ed0-a28c886d6b53.png">

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/new_item.dart
> +  void _onInputEnd(String text) {
это должно быть в bloc

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/new_item.dart
> +  AddTask({required this.onInputEnd, super.key});
const?

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list.dart
> +  TaskList({Key? key}) : super(key: key);
const

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list.dart
> +                )));
trailing comma😭

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list.dart
> +                        RouteMapper.goToEditTask(null, context);
статичная навигация как в GetX?

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list_header_delegate.dart
> +      required this.onSwitchShowDone});
trailing comma

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list_header_delegate.dart
> +  TaskListHeaderDelegate(
const?

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list_header_delegate.dart
> +  @override
между некоторыми кусками кода должны быть отступы, в глаза же сразу бросается

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list_header_delegate.dart
> +  Widget _visibilityIcon(bool showDone, VoidCallback onSwitchShowDone) =>
1 правило Flutter - не возвращай виджеты из функций

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list_item.dart
> +      required this.onDelete})
trailing comma 😭

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list_item.dart
> +  TaskListItem(
const

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list_item.dart
> +                              // WidgetSpan(
комменты, которые потом нужны? чет их оч много

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/task_list_item.dart
> +  Widget? _prioritySign(Importance importance) {
это все должно быть не в ui файлике, а в блоке как минимум

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_edit/presentation/widgets/task_edit.dart
> +                  // DropdownButtonHideUnderline(
как много комментов

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_edit/presentation/widgets/task_edit.dart
> +const testText =
???

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_edit/presentation/widgets/dropdown_list.dart
> +      required this.items,
trailing comma 😭

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_edit/presentation/widgets/dropdown_list.dart
> +  DropdownList(
const

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_edit/presentation/widgets/dropdown_list.dart
> +  @override
отступы

2022-08-07 16:35 UTC, devasidmi commented on lib/features/task_edit/presentation/widgets/dropdown_list.dart
> +  @override
отступы

2022-08-07 16:35 UTC, devasidmi commented on lib/core/presentation/themes/extensions/blue_icon_theme.dart
> +class BlueIconTheme extends ThemeExtension<BlueIconTheme> {
почему это отдельная тема? В теории их всего две должно быть - светлая и темная, но если приложение большое, то уже у модулей свои темы появляются, а тут ты чисто для виджета их делаешь - кмк такое себе решение

2022-08-07 16:35 UTC, devasidmi commented on lib/core/presentation/navigation/route_mapper.dart
> +  static Future<dynamic> goToTaskList(BuildContext context) =>
сомнительная идея делать навигацию на статиках

2022-08-07 16:56 UTC, Zloooy commented on lib/core/data/adapter/color_adapter.dart
> +class ColorAdapter extends TypeAdapter<Color> {
Да, они есть в модели данных из ТЗ, без сохранения могут затереться на сервере при синхронизации.
![изображение](https://user-images.githubusercontent.com/22305646/183302080-1cbf8446-2742-4dd5-b1bf-fdda3d65501c.png)

2022-08-07 19:32 UTC, Zloooy commented on lib/core/data/dto/task_dto.dart
> +    Color? color,
А DateTime и перечисления тоже так десереализовать нельзя?

2022-08-07 20:05 UTC, Zloooy commented on lib/core/data/data_source/network_task_data_source.dart
> +            headers: {'Authorization': 'Bearer ${dotenv.env["TOKEN"]}'}));
Помещено в файл network_constants.dart.

2022-08-07 20:07 UTC, Zloooy commented on lib/core/data/data_source/network_task_data_source.dart
> +      final resp = await _dio.get<Map<String, dynamic>>('/list/$id');
Сделан файл network_constants.dart

2022-08-07 20:08 UTC, Zloooy commented on lib/core/data/dto/task_dto.dart
> +          required String lastUpdatedBy}) = _TaskDto;
Добавил trailing comma

2022-08-07 20:08 UTC, Zloooy commented on lib/core/data/dto/task_dto.dart
> +class TimestampConverter implements JsonConverter<DateTime, int> {
Перенесено в timestamp_converter.dart

2022-08-07 20:09 UTC, Zloooy commented on lib/core/data/repository/task_repository.dart
> +      required LocalTaskDataSource localTaskDataSource})
Добавил trailing comma

2022-08-07 20:09 UTC, Zloooy commented on lib/core/data/repository/task_repository.dart
> +  static const List<String> _texts = [
Удалено, т. к. код больше не понадобится.

2022-08-07 20:09 UTC, Zloooy commented on lib/core/dependency_injection/global_provider.dart
> +                networkTaskDataSource: NetworkTaskDataSource())),
Добавил trailing comma

2022-08-07 20:10 UTC, Zloooy commented on lib/core/domain/entity/task_entity.dart
> +  static TaskEntity blank() {
Добавлены отступы.

2022-08-14 21:21 UTC, Zloooy commented on lib/core/presentation/themes/extensions/blue_icon_theme.dart
> +class BlueIconTheme extends ThemeExtension<BlueIconTheme> {
Отдельные темы убраны из компонентов.

2022-08-14 21:22 UTC, Zloooy commented on lib/core/presentation/themes/extensions/blue_icon_theme.dart
> +class BlueIconTheme extends ThemeExtension<BlueIconTheme> {
Эта и другие расширения с темами удалены, теперь все дополнительные темы завязаны напрямую на цвета.

2022-08-14 21:23 UTC, Zloooy commented on lib/core/presentation/navigation/route_mapper.dart
> +  static Future<dynamic> goToTaskList(BuildContext context) =>
Маршрутизация перенесена в класс NavigationService

2022-08-14 21:24 UTC, Zloooy commented on lib/core/data/dto/task_dto.dart
> +  factory TaskDto.fromJson(Map<String, dynamic> json) =>
Заменено.

2022-08-14 21:26 UTC, Zloooy commented on lib/core/data/dto/task_dto.dart
> +    Color? color,
Color теперь хранится как строка, её формат проверяется при десериализации.

2022-08-14 21:26 UTC, Zloooy commented on lib/features/task_list/presentation/bloc/task_list_event.dart
> +abstract class TaskListEvent {}
Исправлено

2022-08-14 21:27 UTC, Zloooy commented on lib/features/task_list/presentation/widgets/new_item.dart
> +  AddTask({required this.onInputEnd, super.key});
Исправлено

2022-08-14 21:28 UTC, Zloooy commented on lib/features/task_list/presentation/widgets/task_list_header_delegate.dart
> +  Widget _visibilityIcon(bool showDone, VoidCallback onSwitchShowDone) =>
Вынесено в отдельный виджет

2022-08-14 21:28 UTC, Zloooy commented on lib/features/task_list/presentation/widgets/task_list_item.dart
> +                              // WidgetSpan(
Коменты почищены.

2022-08-14 21:29 UTC, Zloooy commented on lib/features/task_edit/presentation/widgets/task_edit.dart
> +const testText =
Удалено.

2022-08-14 21:30 UTC, Zloooy commented on lib/features/task_list/presentation/widgets/task_list_header_delegate.dart
> +  @override
Добавлены отступы.

2022-08-17 21:19 UTC, Zloooy commented on lib/features/task_list/presentation/widgets/new_item.dart
> +  void _onInputEnd(String text) {
Создан AddTaskBloc, управляющий созданием задачи.

2022-08-25 12:30 UTC, devasidmi approved these changes

2022-08-25 12:30 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/visibility_icon.dart
> +            ? SvgPicture.asset('assets/icons/visibility.svg')
можно сделать AssetProvider и вынести туда эти константы

2022-08-25 12:30 UTC, devasidmi commented on lib/features/task_list/presentation/widgets/priority_sign.dart
> +        return SvgPicture.asset('assets/icons/double_exclamation_mark.svg');
ниже про ассеты написал

2022-08-27 10:48 UTC, merged